sonar.projectKey=locos-final
sonar.projectName=locos-Enhan-frontend
sonar.projectVersion=1.0.0

sonar.sources=frontend
sonar.language=JavaScript
sonar.exclusions=**/node_modules/**

sonar.host.url=http://localhost:9000
