sonar.projectKey=locos-final
sonar.projectName=locos
sonar.projectVersion=1.0.0

sonar.sources=Backend,Frontend
sonar.language=JavaScript
sonar.exclusions=**/node_modules/**,dist/**,build/**

sonar.host.url=http://localhost:9000
