sonar.projectKey=locos-final-Backend
sonar.projectName=locos-Enhan-Backend
sonar.projectVersion=1.0.0

sonar.language=JavaScript
sonar.exclusions=**/node_modules/**

sonar.host.url=http://localhost:9000
